add support for targeting iOS simulator on Apple Silicon
bazelbuild/rules_rust pull request #1073
Opened 2021-12-20 07:22 UTC by dae

When building on an Apple Silicon machine, a different target triple
is required to target the simulator:
https://doc.rust-lang.org/rustc/platform-support/aarch64-apple-ios-sim.html

As rules_rust currently ignores abi in triples, listing device
and simulator triples in a rust_repository_set() ends up always using
the first one. Adding this constraint allows a build to be switched
between targeting a device and targeting the simulator.

2021-12-20 16:14 UTC, UebelAndre requested changes
Thanks! Just one question from me

2021-12-20 21:21 UTC, dae commented on rust/platform/triple_mappings.bzl
> +        return ["@build_bazel_apple_support//constraints:simulator"]
From https://github.com/bazelbuild/platforms:

> This repository only includes truly ubiquitous constraints.

> Most common constraints -- that is settings and values that can be used across projects - fall into specific areas like "Apple" or "Java". These are declared in those areas' respective repositories.

> A very few constraints (such as OS and cpu) are relevant for essentially all projects across all areas. These are what this repository is for.

2021-12-21 17:00 UTC, UebelAndre commented on rust/platform/triple_mappings.bzl
> +        return ["@build_bazel_apple_support//constraints:simulator"]
That being said, I still feel a constraint for iOS simulator would make sense in the `@platforms` repo. I'd love for there to be an `abi` section there. But I won't force that change here.

2021-12-21 17:01 UTC, UebelAndre commented
@illicitonion do you think it'd be worth adding `build_bazel_apple_support` to `rust_repositories`? To satisfy the dependency here.

2021-12-22 02:49 UTC, dae commented
FWIW, people who need this likely already have it in their workspace as a transitive dependency of the Apple or Swift rules, so I'm not sure including it as a dependency in rules_rust would buy much.

2022-01-04 18:05 UTC, illicitonion commented
> @illicitonion do you think it'd be worth adding `build_bazel_apple_support` to `rust_repositories`? To satisfy the dependency here.

I could go either way. It's a very lightweight dependency (it itself only depends on skylib)... I'd lean towards including it just to avoid confusion in the future... It'd be great to see this folded into `@platforms` in the future, though, as as-written the `abi_to_constraints` function assumes the only `-sim` is iOS, which feels a little sketchy!

2022-01-04 22:30 UTC, dae commented
It might make sense to have abi_to_constraints() have access to the vendor name in the future to be able to distinguish ambiguous ABI names, but as far as I'm aware nothing else uses 'sim' at the moment.

If you'd like me to update the PR to add the dependency, please let me know.

2022-01-04 22:38 UTC, UebelAndre commented
> If you'd like me to update the PR to add the dependency, please let me know.

My vote would be to add the dependency. If you don't mind 😅

2022-01-04 23:25 UTC, dae commented
Ok, I have the update ready to push:

```patch
diff --git a/WORKSPACE.bazel b/WORKSPACE.bazel
index 429da7f..db7f71f 100644
--- a/WORKSPACE.bazel
+++ b/WORKSPACE.bazel
@@ -35,6 +35,7 @@ rules_rust_test_deps()
 # --- end stardoc

 load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
+load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")

 http_archive(
     name = "bazelci_rules",
@@ -43,6 +44,15 @@ http_archive(
     url = "https://github.com/bazelbuild/continuous-integration/releases/download/rules-1.0.0/bazelci_rules-1.0.0.tar.gz",
 )

+# Make the iOS simulator constraint available, which is referenced in abi_to_constraints()
+# rules_rust does not require this dependency; it is just imported as a convenience.
+maybe(
+    http_archive,
+    name = "build_bazel_apple_support",
+    sha256 = "76df040ade90836ff5543888d64616e7ba6c3a7b33b916aa3a4b68f342d1b447",
+    url = "https://github.com/bazelbuild/apple_support/releases/download/0.11.0/apple_support.0.11.0.tar.gz",
+)
+
 # To run with RBE on Bazel CI, uncomment the following lines.
 #
 # load("@bazelci_rules//:rbe_repo.bzl", "rbe_preconfig")
```

I'm still not sure this is a great idea though. It will potentially cause problems for users down the road, if build_bazel_apple_support changes in incompatible ways. Most users are likely importing this as a transitive dependency of other Apple rules, and currently they can import rules_apple and then rules_rust into their workspace, or vice versa. With the dependency in rules_rust as well, we then either need to make sure we keep it up to date in these rules, or the user could run into troubles if they import rules_rust first, which pulls in an older version of the apple_support libraries that rules_apple does not expect. I'm not sure the increased fragility is worth whatever minor convenience it's providing?

2022-01-04 23:41 UTC, UebelAndre commented
> Ok, I have the update ready to push:

I think the changes should actually go in [@rules_rust//rust:repositories.bzl](https://github.com/bazelbuild/rules_rust/blob/8c0ece8cbe0e246d3a87e8d9d4567cb7582be548/rust/repositories.bzl#L35-L111). 

> I'm still not sure this is a great idea though. It will potentially cause problems for users down the road, if build_bazel_apple_support changes in incompatible ways. Most users are likely importing this as a transitive dependency of other Apple rules, and currently they can import rules_apple and then rules_rust into their workspace, or vice versa. With the dependency in rules_rust as well, we then either need to make sure we keep it up to date in these rules, or the user could run into troubles if they import rules_rust first, which pulls in an older version of the apple_support libraries that rules_apple does not expect. I'm not sure the increased fragility is worth whatever minor convenience it's providing?

I'm not a fan of having references to targets that are never actually provided by the rules themselves. You're right about the workspace ordering but that's not a new issue in Bazel so I'd expect users to be assessing the changes they pull in as they update dependencies to prevent the situation you're describing. While I still feel like it should be added, I'll defer to @illicitonion to be the tie-breaker here 😅

2022-01-06 10:55 UTC, illicitonion commented
Let's add the dependency - the `maybe` means people have a way of overriding to a specific version if they need, and this is a fairly common problem in Bazel which people should hopefully be used to solving (even if it's not a problem exposed with a great UX)

2022-01-06 11:14 UTC, illicitonion approved these changes
Thanks!

2022-01-06 11:34 UTC, illicitonion commented
@dae Please could you merge master / push a rebase and I'll merge? Thanks!

2022-01-06 15:44 UTC, UebelAndre approved these changes

2022-01-07 00:03 UTC, dae commented
Should be good to go now

2022-01-07 00:14 UTC, merged