Create internal rust_binary rule instead of using transitions
bazelbuild/rules_rust pull request #1187
Opened 2022-03-12 01:45 UTC by dfreese

This seems like a cleaner way to break the dependency that rust_binary
has on the process wrapper.  The common args are consumed and modified
to set the process wrapper to None, which is detected and performs the
appropriate switch.  The transitions and settings can then be removed.

2022-03-12 02:16 UTC, ddeville commented
I can confirm that this fixes some cycles I was seeing when querying the bazel dependency graph after #1159.

2022-03-12 15:35 UTC, UebelAndre requested changes
One question but otherwise looks good!

2022-03-12 15:35 UTC, UebelAndre commented on rust/private/rustc.bzl
> +    if ctx.executable._process_wrapper != None:
Is this meaningfully different from:
```suggestion
    if ctx.executable._process_wrapper:
```

2022-03-12 15:35 UTC, UebelAndre commented on rust/private/rust.bzl
> +rust_binary_for_process_wrapper = rule(
small nit
```suggestion
rust_binary_without_process_wrapper = rule(
```

2022-03-12 19:05 UTC, dfreese commented
All of those changes look fine to me.  I'll be able to get back to this later Sunday night, so feel free to update and merge. I think you should have permission.

2022-03-12 22:19 UTC, UebelAndre approved these changes
Thanks for working on this!

2022-03-12 22:19 UTC, merged

2022-03-14 07:58 UTC, hlopko commented
Thanks! Indeed much simpler!