Draft pipeline support. Not sure how to implement the bazel part yet.
bazelbuild/rules_rust pull request #1207
Opened 2022-03-21 14:21 UTC by gigaroby

2022-03-21 23:09 UTC, UebelAndre commented on util/process_wrapper/BUILD.tinyjson
> +load("@//rust/private:rust.bzl", "rust_library_without_process_wrapper")
I know this PR is WIP but just so I don't forget, can you rename this file to `BUILD.tinyjson.bazel` so it's picked up by buildifier?

2022-03-21 23:09 UTC, UebelAndre commented on util/process_wrapper/BUILD.tinyjson
> +load("@//rust/private:rust.bzl", "rust_library_without_process_wrapper")
I know this PR is WIP but just so I don't forget, can you rename this file to `BUILD.tinyjson.bazel` so it's picked up by buildifier?

2022-04-01 13:06 UTC, gigaroby commented on util/process_wrapper/rustc.rs
> +    if let Some(emit) = get_key(parsed.clone(), "emit") {
There were two places where parsed might have been moved. Modified get_key so it takes a reference to the json object and instead clones the string value out of it. WDYT?

2022-04-05 10:42 UTC, scentini approved these changes

2022-04-05 11:01 UTC, hlopko approved these changes

2022-04-05 11:01 UTC, hlopko commented on util/process_wrapper/output.rs
> +                writer.write_all(&to_write.into_bytes())?;
Is `&to_write.into_bytes()` the same as `to_write.as_bytes()`?

2022-04-05 11:02 UTC, hlopko commented
@UebelAndre do you also want to take a look?

2022-04-05 15:30 UTC, UebelAndre requested changes
I mostly have nits but could you also explain "pipelining" to me? What's the workflow that this unblocks?

2022-04-05 15:30 UTC, UebelAndre commented on test/process_wrapper/rustc_quit_on_rmeta.rs
> +#[test]
Can this be moved into a `tests` module?
```suggestion
#[cfg(test)]
mod test {
    #[test]
```

2022-04-05 15:30 UTC, UebelAndre commented on test/process_wrapper/rustc_quit_on_rmeta.rs
> +fn fake_rustc(process_wrapper_args: &[&'static str]) -> String {
Can you document this function?

2022-04-05 15:30 UTC, UebelAndre commented on util/process_wrapper/rustc.rs
> +pub(crate) fn stop_on_rmeta_completion(
nit: Can you add a docstring for this function?

2022-04-05 15:30 UTC, UebelAndre commented on rust/repositories.bzl
> +        name = "tinyjson",
How do folks feel about scoping the name to avoid it impacting users?
```suggestion
        name = "rules_rust_tinyjson",
```

2022-04-05 15:39 UTC, gigaroby commented
@UebelAndre thanks for review :)

> I mostly have nits but could you also explain "pipelining" to me? What's the workflow that this unblocks?

Sure :) Pipelining (in Cargo terms) allows Cargo to unblock a lib -> lib dependency by asking the compiler to emit a metadata file during compilation. When rustc is asked to provide a metadata file, it will produce two files for any given library a .rmeta (the metadata) which is produced quickly and a .rlib (the full object). As soon as Cargo sees the rmeta file, it unblocks all the library targets that depend on that, increasing parallelism. Bazel is (currently) unable to unblock dependencies mid-action so we need two different invocations of the compiler. The first invocation will be killed as soon as the metadata file is produced while the second will continue to completion. The idea is that for rlib -> rlib dependencies we will only run the lightweight metadata invocation, then unblock the dependencies, then compile the full rlib at link time (or whatever other action depends on the full file). You can also read the original rationale for introducing this in Cargo at https://internals.rust-lang.org/t/evaluating-pipelined-rustc-compilation/10199.

I hope this answers your question.

2022-04-07 14:47 UTC, UebelAndre commented on test/process_wrapper/fake_rustc.rs
> +    eprintln!(r#"{{"rendered": "I am a fake rustc\nvery very fake"}}"#);
Can you add a comment about that here? 

Also, tiny nit (and not to be a spoil-sport) but could the message be something a bit more serious sounding? 😅 If you really like it though it's fine to leave as is.

2022-04-10 05:41 UTC, dfreese commented
Ignorant question: if pipelining requires two runs of cargo, instead of building up a way to terminate rustc, could `--emit=metadata` be the only emit value passed in the first invocation?  What would be the technical rationale for actually needing to kill the process?

Related, it seems like having that as always being the first step would cause the build to fail fast, probably solving #428, more-or-less.

2022-04-11 15:52 UTC, gigaroby commented
@UebelAndre are you happy with this change now?

2022-04-11 17:06 UTC, dfreese commented
> Sadly no. As I have found out while working on the bazel side of this (which is still WIP), the CLI invocations of the two compiler instances need to be basically identical for this to work. Changing any of the flags (including stuff unrelated to codegen, like --error-format) causes rustc to not accept the generated .rmeta file once we get to the linking stage where we need the .rlib.

Sad day. Has that been flagged to the rust team?  That seems like something rustc should be able to support.

2022-04-11 18:03 UTC, hlopko commented
In addition to command line flags changing the content of the rlib as @gigaroby explained, there's also a second issue/feature :) `--emit=metadata` and `--emit=metadata,link` produces different `.rmeta` files. The first produces what you know as `cargo check` outputs. Those `.rmeta` files cannot be used for downstream compilations producing object files since they don't contain all the necessary information, they can only be used to emit most (but strictly speaking not all) compilation errors. If you want to use the `.rmeta` files for compilation, you have to use what cargo pipelining does, which is `--emit=metadata,link` (other combinations work too, like `--emit=metadata,mir`, but then you're hitting the first issue). Unsurprisingly, `.rmeta` file is generated faster with `--emit=metadata` than with `--emit=metadata,link`+process termination.

So regarding #428, we could use the metadata files from pipelining for an equivalent of `cargo check`, but those actions will still be slower than using plain `--emit=metadata`.

2022-04-13 13:04 UTC, UebelAndre requested changes
Sorry for the delay. I have one more question and my final set of nits. Generally looks good though, great work and thanks!

2022-04-13 13:04 UTC, UebelAndre commented on util/process_wrapper/output.rs
> +    thread::spawn(move || {
Is it necessary to perform this work concurrently? I've had frustrating experiences with actions actions not playing nice with others by occupying a ton of resources on the host.

2022-04-13 13:04 UTC, UebelAndre commented on test/process_wrapper/fake_rustc.rs
> +// This binary mocks the output of rustc when run with --error-format=json and --json=artifacts.
Oddly, `rustdoc` reads `//!` when it's at the top of a file to describe the module. But one more nit.
```suggestion
//! This binary mocks the output of rustc when run with `--error-format=json` and `--json=artifacts`.

```

2022-04-15 12:55 UTC, UebelAndre approved these changes
Thanks for putting up with all my boring requests! Looks good to me 😄

2022-04-17 02:25 UTC, jsgf commented
BTW, I've successfully implemented Rust pipelining in Buck rules. The key is to not use `--emit metadata`. More details: https://github.com/bazelbuild/rules_rust/issues/228#issuecomment-1100788353

2022-04-19 11:41 UTC, merged