Recognize `edition = "required"` idiom
bazelbuild/rules_rust pull request #1255
Opened 2022-04-11 02:34 UTC by dtolnay

Due to https://github.com/bazelbuild/rules_rust/issues/1251, I have chosen not to define a usable default `edition` for my workspace. See https://github.com/dtolnay/cxx/pull/1035.

This PR is not required in order for the idiom in https://github.com/dtolnay/cxx/pull/1035 to work, but it simply provides a better error message when some target is missing an edition attribute:

#### Before:

```console
$ bazel build ...
INFO: Analyzed 48 targets (5 packages loaded, 548 targets configured).
INFO: Found 48 targets...
ERROR: /git/cxx/BUILD:4:13: Compiling Rust rlib cxx (34 files) failed: (Exit 1): process_wrapper failed: error executing command bazel-out/k8-opt-exec-2B5CBBC6/bin/external/rules_rust/util/process_wrapper/process_wrapper --arg-file bazel-out/k8-opt-exec-2B5CBBC6/bin/third-party/proc-macro2@build.linksearchpaths --arg-file ... (remaining 28 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
error: argument for `--edition` must be one of: 2015|2018|2021. (instead was `required`)

INFO: Elapsed time: 1.251s, Critical Path: 0.14s
INFO: 2 processes: 2 internal.
FAILED: Build did NOT complete successfully
```

#### After:

```console
$ bazel build ...
ERROR: /git/cxx/BUILD:4:13: in rust_library rule //:cxx: 
Traceback (most recent call last):
	File "/home/david/.cache/bazel/_bazel_david/ebce1d0721fb68dda9c70c0dd1405803/external/rules_rust/rust/private/rust.bzl", line 187, column 32, in _rust_library_impl
		return _rust_library_common(ctx, "rlib")
	File "/home/david/.cache/bazel/_bazel_david/ebce1d0721fb68dda9c70c0dd1405803/external/rules_rust/rust/private/rust.bzl", line 285, column 34, in _rust_library_common
		edition = get_edition(ctx, toolchain),
	File "/home/david/.cache/bazel/_bazel_david/ebce1d0721fb68dda9c70c0dd1405803/external/rules_rust/rust/private/rust.bzl", line 122, column 13, in get_edition
		fail("Attribute `edition` is required for {}.".format(ctx.label))
Error in fail: Attribute `edition` is required for //:cxx.
ERROR: Analysis of target '//:cxx' failed; build aborted: Analysis of target '//:cxx' failed
INFO: Elapsed time: 1.206s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (45 packages loaded, 1063 targets configured)
```

2022-04-11 11:31 UTC, illicitonion approved these changes
Thanks for the PR - this LGTM and I think is a nice improvement, I'll give other maintainers the rest of the day to chip in and then merge :)

2022-04-11 12:22 UTC, hlopko approved these changes

2022-04-11 13:25 UTC, dfreese commented
Instead of having a specialized string (`"required"`), would making default edition optional, and having `None` indicate this be more consistent with other optional values in the toolchain?

2022-04-11 14:35 UTC, UebelAndre requested changes
One nit from me, and:

> Instead of having a specialized string (`"required"`), would making default edition optional, and having `None` indicate this be more consistent with other optional values in the toolchain?

I also like this direction.

2022-04-11 21:29 UTC, dtolnay commented on rust/private/rust.bzl
> +def get_edition(ctx, toolchain):
Fixed.

2022-04-11 21:34 UTC, dtolnay commented
I updated this PR, and separately opened #1256 implementing the alternative favored by @dfreese and @UebelAndre.

2022-04-25 16:31 UTC, UebelAndre commented
@dtolnay This one should now be ready to rebase.

2022-04-25 16:38 UTC, dtolnay commented
I would abandon this one at this point, as #1256 has been merged. That PR was intended as an alternative to this one; https://github.com/bazelbuild/rules_rust/pull/1255#issuecomment-1095049266 says *"instead of"*, not *"in addition to"*.

For my personal use case, this:

```python
rust_repositories(version = RUST_VERSION)
```

is gonna be just as good as:

```python
rust_repositories(
    edition = "required",
    version = RUST_VERSION,
)
```

But I'd be happy to rebase if you'd find `edition = "required"` will be beneficial to readers.

2022-04-26 19:48 UTC, dtolnay commented
I went ahead and rebased. I would say the value of this change is smaller after #1256 than it was originally, but perhaps still worthwhile.

2022-04-26 20:43 UTC, dfreese reviewed
I don't have super strong feelings on this, so I'll let the other maintainers make the call as to whether or not this is good to add.

2022-04-26 20:43 UTC, dfreese commented on rust/private/rust.bzl
> +    elif toolchain.default_edition == "required" or not toolchain.default_edition:
I think the order of comparisons would need to be switched to avoid an error (None check first).

2022-05-04 17:28 UTC, dtolnay commented
Other maintainers haven't weighed in one way or another, so I'll close because #1256 by itself covers my needs. :)

2022-05-04 17:28 UTC, closed without merging