Add script to revendor all crates
bazelbuild/rules_rust pull request #2459
Opened 2024-02-03 13:43 UTC by cameron-martin

It seems that vendored crates commonly get out of sync. Re-vendoring seems to currently be a quite manual process, and finding everything to re-vendor is a hassle.

This adds a bash script, `vendor.sh`, that finds all crate vendor rules in all workspaces in this repository and runs them. This significantly improves the workflow for updating these.

This also adds `.bazelrc` files to disable bzlmod to non-bzlmod workspaces, since otherwise bazel 7 create these when re-vendoring.

This also re-vendors all crates (in a separate commit).

2024-02-16 02:20 UTC, UebelAndre requested changes
So sorry I didn't see this sooner, This would be fantastic! Just one request

2024-02-16 02:20 UTC, UebelAndre commented on vendor.sh
Can we put this file in `util` or something? I'd like to keep the root of the repo clean. Maybe `crate_universe` would be better with an accompanied change to some developer docs?

2024-02-16 09:38 UTC, cameron-martin commented on vendor.sh
I've put it in util since there is already a similar script, `repin_all.sh` in there. Where are the developer docs? I couldn't see any except CONTRIBUTING.md, that only seems to contain information about the CLA.

2024-02-16 13:40 UTC, UebelAndre commented on vendor.sh
Maybe https://github.com/bazelbuild/rules_rust/blob/0.39.0/crate_universe/DEVELOPMENT.md ? Maybe that should be replaced by a `CONTRIBUTING.md` though. Docs are kinda weak at the moment.

2024-02-16 14:37 UTC, cameron-martin commented on vendor.sh
Okay done.

2024-02-18 17:34 UTC, UebelAndre approved these changes
Thanks!

2024-02-18 17:35 UTC, merged