crate_universe: Only compile label regex once.
bazelbuild/rules_rust pull request #2751
Opened 2024-07-19 16:36 UTC by criemen

I hit this when profiling for something else, we spent 1.1sec of 1.3sec of `cargo-bazel generate` compiling this regular expression. It seems to be quite bad on the regex compiler, as even compiling it once takes 8ms.

I had to add the `once_cell` crate to unwrap the Result type - the corresponding stdlib function is still nightly-only unfortunately.

2024-07-19 17:42 UTC, criemen commented
Can someone please push the correct, re-vendored dependencies here? I spent now 30min trying to get this to work locally, but it's not working for me.

2024-07-30 21:48 UTC, criemen commented
Revendoring the dependencies helped with some CI jobs, but the BCR jobs still complain about a lockfile being out of date. I ran the suggested command locally in `examples/bzlmod/hello_world`, but that doesn't seem to satisfy CI. Can someone help me out here?

2024-07-31 13:08 UTC, UebelAndre requested changes
Thank you for this! I think there are some extra things you'll need manually to update on the bzlmod side of this. See https://github.com/bazelbuild/rules_rust/issues/2368

2024-07-31 13:08 UTC, UebelAndre commented on crate_universe/Cargo.toml
> +once_cell = "1.19.0"
nit, can you sort this into the list above?

2024-07-31 19:07 UTC, criemen commented
Thanks! CI finally passed on this.
That was harder than expected given the size of the core change...

2024-07-31 20:35 UTC, UebelAndre approved these changes
Thank you! For this change I probably would have just regenerated dependencies for `crate_universe` directly but thank you for going above and beyond here 😄

2024-07-31 20:48 UTC, merged