clippy: make Cc/Rust toolchains optional
bazelbuild/rules_rust pull request #2766
Opened 2024-07-29 10:49 UTC by lummax

In certain situations (cross compilation with `go`) we might not have Cc/Rust toolchains that are available for the transitioned to execution/target platform.

For the linting case with `clippy` it is acceptable to just skip these targets.

See: https://github.com/lummax/rules_rust_clippy_go_cross_reproducer

2024-08-26 14:03 UTC, krasimirgg commented
Looks good! Could you update this resolving the merge conflicts.

2024-08-26 14:04 UTC, krasimirgg approved these changes

2024-08-26 16:43 UTC, UebelAndre requested changes
The example confuses me. Do you have any toolchains registered at all? Doesn't clippy use of the `--sysroot` flag and require a valid sysroot?

2024-10-10 10:28 UTC, lummax commented
> The example confuses me. Do you have any toolchains registered at all? Doesn't clippy use of the `--sysroot` flag and require a valid sysroot?

`--toolchain_resolution_debug=.*` prints:
```
      ToolchainResolution:   Selected @@bazel_tools~cc_configure_extension~local_config_cc//:cc-compiler-k8 to run on execution platform @@platforms//host:host
[...]
      ToolchainResolution:   Selected @@rules_go~~go_sdk~go_default_sdk//:go_linux_amd64-impl to run on execution platform @@platforms//host:host
[...]
      ToolchainResolution:   Selected @@rules_rust~~rust~rust_linux_x86_64__x86_64-unknown-linux-gnu__nightly_tools//:rust_toolchain to run on execution platform @@platforms//host:host
```

2025-03-13 07:18 UTC, lukasoyen commented
I no longer have access to the motivating source tree. Closing.

2025-03-13 07:18 UTC, closed without merging