Build `rust_test` targets using a crate name different from the underlying lib
bazelbuild/rules_rust pull request #2828
Opened 2024-09-02 12:48 UTC by felipeamp

This is a rollforward of
https://github.com/bazelbuild/rules_rust/pull/2803, but behind the `incompatible_change_rust_test_compilation_output_directory` incompatible flag.

This PR also makes `rust_test` put its compilation outputs in the same directory as the `rust_library` rule (i.e. not in a `test-{hash}` subdirectory anymore).

After this change both the `rust_library` and `rust_test` rules will put all its compilation outputs in the same directory, but there won't be any name collisions in non-sandboxed environments (see https://github.com/bazelbuild/rules_rust/pull/1427 for more context).

Issue with context: https://github.com/bazelbuild/rules_rust/issues/2827

2024-09-06 15:18 UTC, UebelAndre requested changes
Thanks! Had a few questions.

2024-09-06 15:18 UTC, UebelAndre commented on test/unit/rust_test_outputs_are_in_subdirectory/BUILD.bazel
Can you replace these tests with another set that demonstrates the expected behavior?

2024-09-06 15:18 UTC, UebelAndre commented on test/rust/src/lib.rs
> -#![crate_name = "hello_lib"]
Why remove this?

2024-09-10 12:18 UTC, felipeamp commented on test/unit/rust_test_outputs_are_in_subdirectory/BUILD.bazel
Done. I've also undeleted this directory, since it still tests current behavior (when the incompatible flag is not set/set to False).

2024-09-10 12:34 UTC, UebelAndre requested changes
Thanks! Could I also get you to make (or modify an existing) issue ticket to track the new incompatibility flag? We have some guidance on https://github.com/bazelbuild/rules_rust/blob/0.49.3/COMPATIBILITY.md#how-to-make-a-backwards-incompatible-change but since this could be a breaking change we try to give users a chance to raise concerns during the rollout. I've been writing mine to look like https://github.com/bazelbuild/rules_rust/issues/2082

2024-09-10 16:22 UTC, felipeamp commented
I have filed an issue for this, see https://github.com/bazelbuild/rules_rust/issues/2827. Is there anything specific that's missing there?

2024-09-11 09:06 UTC, felipeamp commented
I've also fixed the windows tests (that weren't working due to the toolchain binary extension) and added an assert on the directory name as well.

2024-09-11 20:38 UTC, UebelAndre commented
Just gotta resolve the conflicts!

2024-09-12 09:02 UTC, felipeamp commented
All done.

2024-09-12 13:28 UTC, merged