Add wasm64 support.
bazelbuild/rules_rust pull request #2866
Opened 2024-09-12 20:56 UTC by freeformstu

This PR adds support for `wasm64-unknown-unknown` although there are no prebuilt `wasm64-unknown-unknown` rustc toolchains. Compiling for `wasm64` will be left up to anyone using this target triple until we get T2 support for wasm64.

2024-09-12 22:51 UTC, UebelAndre requested changes

2024-09-12 22:51 UTC, UebelAndre commented on rust/platform/platform.bzl
> +        name = "wasm32",
Can you add an alias for backward compatibility?

2024-09-12 22:51 UTC, UebelAndre commented on rust/private/dummy_cc_toolchain/BUILD.bazel
> +TODO(jedmonds@spotify.com): Need to support linking C code to rust code when compiling for wasm32 or wasm64.
What's this TODO and who is this?

2024-09-12 23:01 UTC, freeformstu commented on rust/private/dummy_cc_toolchain/BUILD.bazel
> +TODO(jedmonds@spotify.com): Need to support linking C code to rust code when compiling for wasm32 or wasm64.
I moved this up from the comment below.

2024-09-18 00:04 UTC, UebelAndre commented
I think the failing windows example is Ok to disable with a reference to:
- https://github.com/bazelbuild/rules_rust/issues/2878

2024-09-18 00:14 UTC, UebelAndre requested changes
`wasm64-unknown-unknown` doesn't have a `std` artifact according to https://doc.rust-lang.org/nightly/rustc/platform-support.html#tier-3

This would lead to failures in analysis (failing to fetch an artifact that doesn't exist) should anything match that platform. I think it should be removed as a default platform and users can use `crates_repository.supported_platform_triples` if they were to have a usable toolchain.

2024-09-18 00:18 UTC, UebelAndre approved these changes

2024-09-18 00:46 UTC, merged