Allowlist more clang flags in bindgen
bazelbuild/rules_rust pull request #2902
Opened 2024-09-26 10:11 UTC by hlopko

Especially `--target` is very usable for cross-compilation use cases.

2024-09-26 11:10 UTC, krasimirgg commented
could you look into the failing CI? Looks related.

2024-09-26 12:10 UTC, krasimirgg requested changes
(just marking as needs attn)

2024-10-01 06:36 UTC, hlopko commented
The CI is green now, thanks for the ping!

2024-10-01 08:57 UTC, krasimirgg approved these changes

2024-10-01 09:17 UTC, merged