Replace symlinks in the output of cargo build scripts
bazelbuild/rules_rust pull request #3067
Opened 2024-12-09 10:01 UTC by havasd

#2948 breaks building of rdkafka with `cmake` because of dangling symlinks.

When building with altest version we get the following error:
```
ERROR: /home/wincent/.cache/bazel/_bazel_wincent/394c4c1d21c5490d4a70260a2cfccaf5/external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/BUILD.bazel:68:19: error while validating output tree artifact external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/_bs.out_dir: child lib/cmake/RdKafka/FindLZ4.cmake is a dangling symbolic link
ERROR: /home/wincent/.cache/bazel/_bazel_wincent/394c4c1d21c5490d4a70260a2cfccaf5/external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/BUILD.bazel:68:19: Running Cargo build script rdkafka-sys failed: not all outputs were created or valid
Target @@rules_rust~~crate~crates__rdkafka-0.37.0//:rdkafka failed to build
Use --verbose_failures to see the command lines of failed build steps.
ERROR: /home/wincent/.cache/bazel/_bazel_wincent/394c4c1d21c5490d4a70260a2cfccaf5/external/rules_rust~~crate~crates__rdkafka-sys-4.8.0-2.3.0/BUILD.bazel:18:13 Compiling Rust rlib rdkafka_sys v4.8.0+2.3.0 (7 files) failed: not all outputs were created or valid
```

2024-12-10 22:31 UTC, illicitonion reviewed
Hmm... Do you know what the symlink is pointing at which is missing? In generally we want to preserve symlinks if possible - is it a symlink to an absolute path? Or a relative path inside in the outdir? Or a relative path inside the sandbox?

2024-12-11 08:06 UTC, havasd commented
> Hmm... Do you know what the symlink is pointing at which is missing? In generally we want to preserve symlinks if possible - is it a symlink to an absolute path? Or a relative path inside in the outdir? Or a relative path inside the sandbox?

It was an absolute path symlink. Essentially when cmake installs the header files as is. So if they were symlinks it will keep them symlinks. It means that due to the linked change now we symlink the runfiles instead of copying therefore nearly all of the native code dependencies will have absolute path symlinks to the sandbox.

I can try to make some change so that relative symlinks in the outdir is preserved.

2024-12-11 22:54 UTC, illicitonion commented
Yeah, I think inlining absolute symlinks feels a lot more reasonable - it's still not obviously the correct semantics, but it's probably reasonable to do. Thanks!

2024-12-14 13:14 UTC, illicitonion reviewed
Looks good, thanks! One last piece - can you add a couple of tests to https://github.com/bazelbuild/rules_rust/tree/0.55.6/test/cargo_build_script? I'm imagining:

1. A cargo_build_script which writes a tempfile to `/tmp/` with some contents, symlinks to it in $OUT_DIR, then a rust_test which `include!`s the $OUT_DIR path and sees the contents is correct, and which `lstat`s with `$OUT_DIR` path and checks it's a file not a symlink
2. The same test, but which writes another file into $OUT_DIR with some contents, creates a relative symlink pointing at the other file in $OUT_DIR, and which does the same checks but checks it's a symlink not a file

2024-12-14 23:07 UTC, havasd commented
I have added tests

2024-12-16 22:37 UTC, havasd commented
Some recent changes broke the windows tests for some reason. Not sure if it has other regressions as well

2024-12-18 01:27 UTC, illicitonion commented
@UebelAndre You have a lot more context than I do here - can you weigh in on this vs https://github.com/bazelbuild/rules_rust/pull/3111 vs something else?

2024-12-31 19:25 UTC, havasd commented
@UebelAndre if you have some time could you please review this PR?

2025-01-02 05:31 UTC, UebelAndre commented
I can take a look this week!

2025-01-03 16:15 UTC, havasd commented on test/cargo_build_script/resolve_abs_symlink_out_dir/test.rs
> +    let data = include_str!(concat!(env!("OUT_DIR"), "/relative_symlink.txt"));
This was the most reliable test where I could come up. Mainly because the test environment is really random where it is tested and I could hardly make it work everywhere by checking the symlink's reference.

2025-01-03 19:16 UTC, UebelAndre commented on test/cargo_build_script/resolve_abs_symlink_out_dir/test.rs
> +    let data = include_str!(concat!(env!("OUT_DIR"), "/relative_symlink.txt"));
Maybe adding a unit test to `cargo_build_script/bin.rs` would make that easier?

2025-01-03 19:17 UTC, UebelAndre requested changes
CI seems to have flaked so this will need one more push. But if you also have time to look into https://github.com/bazelbuild/rules_rust/pull/3067/files#r1902089155 that'd be sweet!

2025-01-03 21:04 UTC, havasd commented on test/cargo_build_script/resolve_abs_symlink_out_dir/test.rs
> +    let data = include_str!(concat!(env!("OUT_DIR"), "/relative_symlink.txt"));
okay, I have added unit tests

2025-01-03 21:40 UTC, UebelAndre approved these changes
Awesome! Thank you so much!

2025-01-03 21:46 UTC, merged

2025-01-06 20:59 UTC, spags-lacework commented
Thanks for fixing this. Do you know when you will do include this in a new version of rules_rust?