Migrate to the modern linker input API.
bazelbuild/rules_rust pull request #463
Opened 2020-10-23 04:44 UTC by benjaminp

See https://github.com/bazelbuild/bazel/issues/10860.

2020-10-23 07:18 UTC, illicitonion approved these changes
Thanks!

Do you know what the minimum version of Bazel this supports is?

2020-10-23 13:00 UTC, benjaminp commented
3.0.0

2020-10-23 13:55 UTC, dfreese commented
docs/index.md mentions 0.26.0, so that should probably be updated.  I don't have a good way of verifying 0.26.0 still works.

2020-10-27 07:21 UTC, UebelAndre commented
Does anyone know what it would take to remove `legacy_cc_starlark_api_shim.bzl `?

2020-10-27 14:48 UTC, benjaminp commented
It should probably just be renamed or inlined into the callers as desired.

2020-10-27 14:59 UTC, UebelAndre commented
So this pull request addresses the usage of any legacy/deprecated behavior in this file?

2020-10-27 15:07 UTC, benjaminp commented
Yes.

2020-10-27 15:57 UTC, UebelAndre commented
Would it make sense to move those methods into `rust/private/utils.bzl` then?

2020-10-27 16:28 UTC, benjaminp commented
Probably. I can do that in this PR if you like.

2020-10-27 16:33 UTC, UebelAndre commented
I think that'd be a nice improvement but I leave it up to @illicitonion and @dfreese 😃

2020-11-04 05:03 UTC, UebelAndre commented
@damienmg do you have time during your day today to check this out?
@benjaminp If the "legacy" aspect of the modified files no longer applies, could you move the code to `rust/private/utils.bzl`?

2020-11-04 08:31 UTC, damienmg requested changes

2020-11-04 08:31 UTC, damienmg commented on docs/index.md
> +The rules are under active development, as such the lastest commit on the master branch should be used. `master` currently requires Bazel >= 3.0.0.
I think https://github.com/bazelbuild/rules_rust/blob/master/workspace.bzl#L5 should be updated too.

2020-11-05 04:24 UTC, UebelAndre requested changes

2020-11-05 04:24 UTC, UebelAndre commented on rust/private/legacy_cc_starlark_api_shim.bzl
> +    linker_inputs = dep[CcInfo].linking_context.linker_inputs.to_list()
Can you delete this file and move the contents into `util.bzl`?

2020-11-05 04:30 UTC, UebelAndre commented on rust/private/legacy_cc_starlark_api_shim.bzl
> +    linker_inputs = dep[CcInfo].linking_context.linker_inputs.to_list()
🙏

2020-11-05 04:31 UTC, UebelAndre approved these changes

2020-11-05 08:37 UTC, illicitonion approved these changes
LGTM

We should probably try to set up CI running the claimed minimum supported version at some point, but that's definitely not a matter for this PR :)

Over to @damienmg to merge!

2020-11-05 09:00 UTC, damienmg approved these changes

2020-11-05 09:02 UTC, damienmg commented
> LGTM
> 
> We should probably try to set up CI running the claimed minimum supported version at some point, but that's definitely not a matter for this PR :)

Yes unfortunately this is a large task as the bazel CI is unlikely to do so. Also Bazel 4 is supposed to be a LTS and I would expect they would test rules with LTS for the support duration of the LTS. At which point the minimal version should always probably be the oldest LTS still supported. 

> 
> Over to @damienmg to merge!

Done 👍 
Thanks for the contributions!

2020-11-05 09:03 UTC, damienmg commented
Sorry for merging, I spoke too fast. We need to wait a bit more to see if the rebasing worked.

2020-11-05 09:11 UTC, merged