Enables runtime linking for darwin platforms
bazelbuild/rules_rust pull request #766
Opened 2021-06-12 03:27 UTC by csmulhern

Runtime linking with rpaths works correctly on darwin with only this change, for dylibs that have the correct extension (dylib) and the correct rpath configuration. Runtime linking against dynamic libraries created by bazel targets remains broken, due to them not having install names set correctly. That is fixed by using --incompatible_macos_set_install_name after https://github.com/bazelbuild/bazel/pull/13427.

I have attached a zip file with a simple example workspace demonstrating this.

[example.zip](https://github.com/bazelbuild/rules_rust/files/6641587/example.zip)

Run:
```bash
(cd lib; ./build.sh)
bazel run //:main
```

2021-06-13 20:00 UTC, UebelAndre commented
Seems related to https://github.com/bazelbuild/rules_rust/issues/540

2021-06-13 20:03 UTC, UebelAndre requested changes
Thanks for the PR! I think this looks good but do you think you could Bazelify the example you have and add it to `examples/runtime_linking` or something so we can be sure to avoid potential regressions in the future 😅 🙏?

2021-06-13 20:20 UTC, csmulhern commented
My intention is to fix #621 and so this will be bazel-ified and checked by CI by those targets. The difficulty with adapting the example I have linked here is that it requires using an unreleased version of Bazel so that --incompatible_macos_set_install_name can be set. Otherwise I'd need to write a new rule that post processes cc_library targets to set the install name of the dylib, which I'm not sure is worth the effort. I wanted to submit this PR independently because it is preventing me from linking against a vulkan dylib that I am cc_importing in my project, ahead of a full fix for #621. I can also wait to submit a PR with a full fix for #621, which involves:

1) Setting --incompatible_macos_set_install_name (which will work correctly in an upcoming release of Bazel, hopefully 4.2: https://github.com/bazelbuild/bazel/issues/13558#issuecomment-859973642).
2) This change.
3) The change outlined in my second paragraph here: https://github.com/bazelbuild/rules_rust/issues/621#issuecomment-832382072.

This will specifically solve the issues with the tests in @examples/ffi/rust_calling_c/BUILD.bazel on macOS.

To resolve the issues with the tests in @examples/ffi/rust_calling_c/simple/BUILD.bazel, we also need to resolve #741, which I believe should be resolved by using the dynamic library specified by the cc toolchain. I also plan to take a look at this.

2021-06-14 14:10 UTC, illicitonion approved these changes
Works for me - maybe worth a comment above the if statement explaining that darwin doesn't work before (link to PR/commit) and that it's known not to work <4.2

2021-06-14 14:31 UTC, UebelAndre approved these changes
I see, thanks! I agree with https://github.com/bazelbuild/rules_rust/pull/766#pullrequestreview-682960848 but otherwise looks good and am excited to see this issue getting fixed 😄

2021-06-14 23:16 UTC, csmulhern commented
Done.

2021-06-14 23:17 UTC, UebelAndre approved these changes
Thank you so much!

2021-06-14 23:21 UTC, merged