fix: load providers from //:providers.bzl
bazelbuild/rules_rust pull request #953
Opened 2021-09-22 15:54 UTC by manekinekko

**BREAKING CHANGE**: `@build_bazel_rules_nodejs//:declaration_provider.bzl` has been deleted; load from `@build_bazel_rules_nodejs//:providers.bzl` instead. See https://github.com/bazelbuild/rules_nodejs/commit/cc648183160832b1540c3893963e8ef4a45e4220

2021-09-22 16:06 UTC, UebelAndre commented
Thanks for fixing this! I think you'll also need to update the `docs/BUILD.bazel`:
https://github.com/bazelbuild/rules_rust/blob/e589105b4e8181dd1d0d8ccaa0cf3267efb06e86/docs/BUILD.bazel#L7-L19

2021-09-22 16:38 UTC, UebelAndre requested changes

2021-09-22 16:38 UTC, UebelAndre commented on docs/BUILD.bazel
> +        "@build_bazel_rules_nodejs//:providers:bzl",
Typo maybe?
```suggestion
        "@build_bazel_rules_nodejs//:providers.bzl",
```

2021-09-22 16:40 UTC, UebelAndre commented
It seems the rolling release builds are unable to start? Doesn't seem like this change would impact that.
cc @hlopko @philwo

2021-09-22 18:15 UTC, philwo commented
macOS workers do not yet have a new enough version of Bazelisk yet to support rolling releases. Will fix that next week.

RBE Rolling Bazel seems like some issue with the container config maybe. @coeuvre any idea?

2021-09-23 18:46 UTC, manekinekko commented on docs/BUILD.bazel
> +        "@build_bazel_rules_nodejs//:providers:bzl",
Good catch! Thank you.

2021-09-23 19:04 UTC, UebelAndre commented
@manekinekko Seems like `providers.bzl` is not publicly visible?
```
in bzl_library rule //:docs_deps: target '@build_bazel_rules_nodejs//:providers.bzl' is not visible from target '//:docs_deps'. Check the visibility declaration of the former target if you think the dependency is legitimate. To set the visibility of that source file target, use the exports_files() function
```
Maybe that's an oversight in `rules_nodejs`?

2021-09-25 12:52 UTC, manekinekko commented
Weird! I am using v4.2.0. Maybe that's why it's working for me.

```bazel
http_archive(
    name = "build_bazel_rules_nodejs",
    sha256 = "4e1a5633267a0ca1d550cced2919dd4148575c0bafd47608b88aea79c41b5ca3",
    urls = ["https://github.com/bazelbuild/rules_nodejs/releases/download/4.2.0/rules_nodejs-4.2.0.tar.gz"],
)
```

cc @alexeagle @gregmagolan

2021-09-27 16:30 UTC, alexeagle commented
Hi @manekinekko nice to see you again :)

```
ERROR: /workdir/docs/BUILD.bazel:7:12: in bzl_library rule //:docs_deps: target '@build_bazel_rules_nodejs//:providers.bzl' is not visible from target '//:docs_deps'. Check the visibility declaration of the former target if you think the dependency is legitimate. To set the visibility of that source file target, use the exports_files() function
```
this is because you're referencing the providers.bzl file directly, instead you should use some `filegroup` target in that package that exposes all the files (probably named "bzl")

2021-09-28 13:46 UTC, manekinekko commented
Thank you for the hint @alexeagle ❤️

@UebelAndre looks the `bzl_library` rule needs to be updated as well. Do you need to fix that?

https://github.com/bazelbuild/rules_rust/blob/e589105b4e8181dd1d0d8ccaa0cf3267efb06e86/docs/BUILD.bazel#L07-L12

2021-09-29 08:00 UTC, coeuvre commented
RBE Rolling Bazel issue is fixed by https://github.com/bazelbuild/rules_rust/pull/958.

2021-11-08 17:27 UTC, UebelAndre commented
Closing this in favor of https://github.com/bazelbuild/rules_rust/pull/984

2021-11-08 17:27 UTC, closed without merging